### ISSUE TITLE
ImageStorage Resolver

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/On-Demand-Car-Servicing-Backend#39]

**Comment by HowardYaw** [comment]
[Guides for upload image to AWS S3 Bucket](https://medium.com/codespace69/graphql-typescript-upload-a-base64-image-data-from-nodejs-to-aws-s3-bucket-d84cbe34421b)

**Comment by HowardYaw** [comment]
[Guide for upload to firebase storage via React Native](https://medium.com/@joananespina/uploading-to-firebase-storage-with-react-native-39f4a500dbcb)
