### ISSUE TITLE
VideoStorage Resolver

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/On-Demand-Car-Servicing-Backend#43]

**Comment by HowardYaw** [comment]
[Upload Pictures and Video to AWS](https://medium.com/@aurelie.lebec/uploading-pictures-and-videos-from-your-phone-in-your-app-with-react-native-expo-cloudinary-and-d3ad4358e81a)

**Comment by HowardYaw** [comment]
[Upload Image to server](https://heartbeat.fritz.ai/how-to-upload-images-in-a-react-native-app-4cca03ded855)
